Repository shanearcaro/cs490, pull requests merged in 2022-10, with the labels that each got.

#23 Fixed database error preventing question inserts
  docker/database/init.sql
  src/backend/insertQuestion.php
  src/frontend/post/sendQuestion.php
Labels: enhancement

#29 Created a back button script and a student landing page
  src/frontend/StudentPages/student.php
  src/frontend/StudentPages/studentBackButton.php
  src/frontend/StudentPages/takeExam.php
  src/frontend/TeacherPages/createExam.php
  src/frontend/TeacherPages/questionBank.php
  src/frontend/TeacherPages/teacher.php
  src/frontend/TeacherPages/teacherBackButton.php
  style/exam.css
Labels: enhancement

#31 Fixed student pages after landing page revisions
  src/frontend/StudentPages/student.php
  src/frontend/StudentPages/takeExam.php
  src/frontend/TeacherPages/createExam.php
  src/frontend/post/sendExam.php
Labels: bug

#38 Auto grader completed
  docker/Dockerfile
  docker/database/init.sql
  src/backend/insertCompletedExam.php
  src/backend/selectCompletedExam.php
  src/backend/selectExamsTeacher.php
  src/backend/updateScore.php
  src/frontend/StudentPages/takeExam.php
  src/frontend/TeacherPages/createExam.php
  src/frontend/TeacherPages/examReview.php
  src/frontend/TeacherPages/gradeExam.php
  src/frontend/post/sendGrade.php
  src/frontend/post/sendLogin.php
  src/middle/autoGrader.php
  src/middle/question.py
  style/examReview.css
Labels: request

#41 Routing finally done
  docker/Dockerfile
  docker/database/init.sql
  src/backend/insertCompletedExam.php
  src/backend/selectExamResults.php
  src/backend/selectStudentExams.php
  src/backend/updateScore.php
  src/frontend/StudentPages/results.php
  src/frontend/StudentPages/reviewExam.php
  src/frontend/TeacherPages/examReview.php
  src/frontend/post/sendGrade.php
  src/middle/question.py
  style/examReview.css
Labels: request
